seed: 829127
eval_analytic: TRUE
eval_mcmc: TRUE
model: "slope"

# T-step
omega_t: 0.5
c_gt: -2
sigma_a_values: !expr c(0.5, 1)
mu_t0: 0
sigma_t0: 10
adapt_delta_t_step: 0.8

# I-step
omega_i_gt_values: !expr c(-0.5)
omega_i_range : !expr c(-1.5, 0.5, 0.05)

sigma_i: 0.1
mu_i0: 0
sigma_i0: 5
r_tol: !expr 1e-5

# point
adapt_delta_point: 0.99

# E-lik
adapt_delta_e_lik: 0.99
numint_lower_c_e_lik: -6
numint_upper_c_e_lik: 6

# E-post
adapt_delta_e_post: 0.99
n_c_skip: 5
numint_lower_c_e_post: -20
numint_upper_c_e_post: 20
numint_lower_w_e_post: -6
numint_upper_w_e_post: 6

# E-log-lik
adapt_delta_e_log_lik: 0.99
numint_lower_c_e_log_lik: -4
numint_upper_c_e_log_lik: 0
