seed: 4
surrogate_model: "pce"

# s-step
n_sims: !expr c(10, 30, 50)
sigma_sim: 0.001

# i-step
w_exp_gts: !expr c(-0.05)
sigma_exp: 0.01
n_exp: 5
lower_w_exp: -1
upper_w_exp: 1
use_clustering: TRUE
number_clusters: 25
propagate_sigma_a: TRUE

# PCE
poly_degree: 5
M: 1

# stan
refresh_cmdstan: 0
adapt_delta: 0.99
chains: 4
iter_sampling: 400
iter_warmup: 100
