seed: 8291
surrogate_model: "pce"

# sbc
n_sims_sbc_s: 10
n_sims_sbc_i: 20
keep_fits: FALSE

# s-step
n_sims: !expr c(8, 9, 10, 15, 20, 30, 40)
sigma_sim: !expr c(0.01)

# i-step
n_exp: 5
lower_w_exp: -1
upper_w_exp: 1
use_clustering: TRUE
number_clusters: 25
propagate_sigma_a: TRUE

# PCE
poly_degree: 5
M: 1

# stan
refresh_cmdstan: 0
adapt_delta: 0.99
chains: 4
iter_sampling: 1000
iter_warmup: 1000
